### ISSUE TITLE
Create multiple events

### ISSUE THREAD

**Issue by Code-Divine** [davaxi/VCalendar#1]
How to create calendar with multiple events with this.

**Comment by davaxi** [comment]
Currently it is not possible to put several events on the same ics file. I do not think it's the policy of the file even though it would seem to be possible: http://stackoverflow.com/questions/1823647/grouping-multiple-events-in-a-single-ics-file-icalendar-stream.

It is necessary to see to update the librairy in order to be able to put several events in the same file ics. And see how Google Calendar / GMail / Outlook / iCal behave.

What is the practical case?

**Comment by apphancer** [comment]
This would be really useful. At the moment I see this being a big limitation
